---
- name: add subscription
  command: subscription-manager attach --pool {{ poolid }}

- name: disable all repos
  command: subscription-manager repos --disable '*'

- name: enable RHEL + RHDS repos
  command: subscription-manager repos --enable rhel-7-server-rpms --enable rhel-7-server-rhds-10-rpms
