---
- name: install base group
  yum: name=@base state=present

- name: install RHDS
  yum: name={{item}}
  with_items:
    - redhat-ds
    - xorg-x11-xauth
    - dejavu*

- name: configure firewall
  firewalld: port={{item}} permanent=true state=enabled
  with_items:
    - 389/tcp
    - 636/tcp
    - 9830/tcp
  notify: restart firewalld
